#!/bin/bash


echo -e '\n\t\t Copying custom homepage to PSYPI. \n'
sleep 1s

rsync -Phiame ssh /home/psyburr/.psyfiles/git/psypi.onthewifi/ psypi:/var/www/ \
	--stats --no-p --no-g --no-t \
	--exclude={'.git','sync2psypi'} \
	--chown=www-data:www-data

echo -e '\n\t\t Synchronization task is complete.\n'
sleep 1s
exit
