#!/bin/bash


echo -e '\n\t\t Copying custom homepage to PSYPI. \n'
sleep 1s

rsync -Phiame ssh /home/psyburr/.psyfiles/mycustombrowser/psydomehome/ \
	psypi:/var/www/ --stats --no-p --no-g --no-t --size-only

echo -e '\n\t\t Synchronization task is complete.\n'
sleep 1s
exit
